sudo: false

dist: xenial

language: php

php:
  - 7.4
  - 7.3
  - 7.2

before_script:
  - mkdir -p build/logs
  - composer install --dev --no-interaction
  
script:
  - composer cover
  
after_script:
  - composer coveralls
