sudo: false

dist: xenial

language: php

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6

matrix:
  include:
    - php: "5.5"
      dist: precise
    - php: "5.4"
      dist: trusty
    - php: "5.3"
      dist: precise

before_script:
  - mkdir -p build/logs
  - composer install --dev --no-interaction
  
script:
  - ./vendor/bin/phpunit --bootstrap ./tests/bootstrap.php -c tests/phpunit.xml --coverage-clover build/logs/clover.xml tests
  
after_script:
  - php ./vendor/bin/coveralls -v
